/**
 * generated by Xtext
 */
package maxim.zaks.ui.contentassist;

import maxim.zaks.ui.contentassist.AbstractFlatBuffersProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class FlatBuffersProposalProvider extends AbstractFlatBuffersProposalProvider {
}
