/*
 * generated by Xtext
 */
package maxim.zaks;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class FlatBuffersUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return maxim.zaks.ui.internal.FlatBuffersActivator.getInstance().getInjector("maxim.zaks.FlatBuffers");
	}
	
}
