/*
 * generated by Xtext
 */
package maxim.zaks.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class FlatBuffersUiModule extends maxim.zaks.ui.AbstractFlatBuffersUiModule {
	public FlatBuffersUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
