/*
 * generated by Xtext
 */
package maxim.zaks;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class FlatBuffersRuntimeModule extends maxim.zaks.AbstractFlatBuffersRuntimeModule {

}
