/*
 * generated by Xtext
 */
package maxim.zaks.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractFlatBuffersValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(maxim.zaks.flatBuffers.FlatBuffersPackage.eINSTANCE);
		return result;
	}
}
